
const c=document.getElementById("game"), ctx=c.getContext("2d");
const roster=[
 {name:"Chris Dempsey",nick:"DEMPS",num:"35",role:"Pylon Mode",color:"#e8eef0",trim:"#20c4c9",speed:60,hustle:85,shot:55,pass:1,stick:45,special:"1% BACKHAND",desc:"Slow feet. Big heart. Cold beer."},
 {name:"Andy Duran",nick:"FREIGHT TRAIN",num:"8",role:"Two-Way D",color:"#f6f3e8",trim:"#0e8f42",speed:80,hustle:92,shot:82,pass:78,stick:76,special:"BONE CRUSHER",desc:"Hits. Blocks. Chirps. Sets the tone."},
 {name:"Lenny Owens",nick:"SILK HANDS",num:"08",role:"Playmaker",color:"#efe5cf",trim:"#f0b23e",speed:94,hustle:82,shot:60,pass:94,stick:92,special:"ANKLE PASS",desc:"Pass harder than his slap shot."},
 {name:"Suman Chakrabarti",nick:"SHOE",num:"19",role:"Smile Boost",color:"#20a64a",trim:"#ffd53b",speed:52,hustle:75,shot:45,pass:95,stick:72,special:"SMILE BOOST",desc:"Slow as molasses. Passes on time."},
 {name:"Avery Duran",nick:"BONES",num:"11",role:"Game Breaker",color:"#11151b",trim:"#48a6c8",speed:97,hustle:100,shot:84,pass:90,stick:90,special:"BONES MODE",desc:"18 years old. Pure speed. Pure hustle."},
 {name:"Mark Townsend",nick:"TOWNSIE",num:"38",role:"Chaos Goalie",color:"#d9dde2",trim:"#2d65b2",speed:58,hustle:88,shot:20,pass:45,stick:55,special:"FLOP SAVE",desc:"Glove side vacation. Yells a lot."},
 {name:"Hudson Townsend",nick:"HUDSIE",num:"13",role:"Team Protector",color:"#d8e0e7",trim:"#17834c",speed:78,hustle:91,shot:68,pass:80,stick:87,special:"DEFEND DAD",desc:"Two-way threat. Protects Townsie."},
 {name:"Kaden Chakrabarti",nick:"HONEY BADGER",num:"23",role:"Left Wing",color:"#07182b",trim:"#27c7c9",speed:93,hustle:97,shot:78,pass:92,stick:98,special:"PHONE BOOTH",desc:"18. 5'7. Handles in traffic. Never backs down."}
];

let mode="select", sel=0, keys={}, last=performance.now();
let player={x:145,y:270,vx:0,vy:0,face:1,boost:0};
let mate={x:320,y:210,vx:0,vy:0};
let puck={x:260,y:270,vx:0,vy:0};
let goalie={x:850,y:270,dir:1};
let defenders=[], particles=[], score=0,timeLeft=75,msg="",msgT=0,cool=0,hitMeter=0,combo=0;

function resetDefenders(){defenders=[{x:510,y:180,vx:0,vy:0,stun:0},{x:610,y:350,vx:0,vy:0,stun:0}];}
function start(){mode="play";score=0;timeLeft=75;cool=0;hitMeter=0;combo=0;player={x:145,y:270,vx:0,vy:0,face:1,boost:0};mate={x:320,y:210,vx:0,vy:0};puck={x:260,y:270,vx:0,vy:0};goalie={x:850,y:270,dir:1};resetDefenders();say("SCORE 3. HIT 2. WIN SATURDAY.",2);}
addEventListener("keydown",e=>{const k=e.key.toLowerCase();keys[k]=true;if(mode==="select"){if(k==="arrowleft"||k==="a")sel=(sel+roster.length-1)%roster.length;if(k==="arrowright"||k==="d")sel=(sel+1)%roster.length;if(e.key==="Enter")start();}else{if(e.key==="Escape")mode="select";if(e.code==="Space")shoot();if(k==="x")pass();if(e.key==="Shift")special();if(mode==="done"&&e.key==="Enter")start();}});
addEventListener("keyup",e=>keys[e.key.toLowerCase()]=false);
function say(t,n=1){msg=t;msgT=n;}
function txt(t,x,y,s=16,col="#fff",a="left"){ctx.fillStyle=col;ctx.font=`bold ${s}px monospace`;ctx.textAlign=a;ctx.fillText(t,x,y);}
function bar(label,val,x,y,w=120){txt(label,x,y,13,"#ddd");ctx.strokeStyle="#344";ctx.strokeRect(x+55,y-11,w,9);ctx.fillStyle=val>=95?"#19d7d7":val>=85?"#5bd95b":val>=70?"#e5b03d":"#d95151";ctx.fillRect(x+55,y-11,w*val/100,9);txt(val,x+55+w+8,y,13,"#fff");}
function rect(x,y,w,h,col){ctx.fillStyle=col;ctx.fillRect(x,y,w,h);}
function card(p,x,y,w,h,on){rect(x,y,w,h,on?"#102a3d":"#11161d");ctx.strokeStyle=on?"#46d7ff":p.trim;ctx.lineWidth=on?5:2;ctx.strokeRect(x,y,w,h);drawPixelSkater(x+w/2,y+70,p,1.05,1);txt("#"+p.num,x+12,y+25,23,p.trim);txt(p.nick,x+w/2,y+24,15,"#f5dfb0","center");txt(p.role,x+w/2,y+h-14,13,p.trim,"center");}
function drawPixelSkater(x,y,p,s=1,face=1){ctx.save();ctx.translate(x,y);ctx.scale(s*face,s);ctx.fillStyle=p.color;ctx.strokeStyle=p.trim;ctx.lineWidth=3;ctx.fillRect(-17,-24,34,42);ctx.strokeRect(-17,-24,34,42);ctx.fillStyle="#111";ctx.fillRect(-15,18,12,25);ctx.fillRect(3,18,12,25);ctx.fillStyle="#111";ctx.beginPath();ctx.arc(0,-40,15,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#ddd";ctx.strokeRect(-11,-46,22,13);ctx.fillStyle=p.trim;ctx.font="bold 14px monospace";ctx.textAlign="center";ctx.fillText(p.num,0,2);ctx.strokeStyle="#d6c9aa";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-8,6);ctx.lineTo(28,42);ctx.stroke();ctx.restore();}
function drawGoalie(){drawPixelSkater(goalie.x,goalie.y,roster[5],1.15,-1);ctx.fillStyle="#d9dde2";ctx.fillRect(goalie.x-22,goalie.y+25,16,42);ctx.fillRect(goalie.x+8,goalie.y+25,16,42);}
function rink(){rect(0,0,960,540,"#ddecf5");rect(30,80,900,380,"#c5ddeb");ctx.strokeStyle="#93b9ce";ctx.lineWidth=3;ctx.strokeRect(30,80,900,380);ctx.strokeStyle="#d33";ctx.beginPath();ctx.moveTo(145,80);ctx.lineTo(145,460);ctx.moveTo(815,80);ctx.lineTo(815,460);ctx.stroke();ctx.strokeStyle="#315";ctx.strokeRect(865,210,45,120);}
function shoot(){const p=roster[sel];if(dist(puck,player)<72){puck.vx=player.face*(7+p.shot/8+hitMeter/20);puck.vy=(puck.y-player.y)*.06;hitMeter=0;say(p.nick+": ROCKET!",.8);burst(puck.x,puck.y,p.trim,10);}}
function pass(){const p=roster[sel];if(dist(puck,player)<78){let dx=mate.x-puck.x,dy=mate.y-puck.y,m=Math.hypot(dx,dy)||1;puck.vx=dx/m*(5+p.pass/12);puck.vy=dy/m*(5+p.pass/12);say(p.nick==="HONEY BADGER"?"SAUCER THROUGH TRAFFIC!":"PASS!",1);}}
function special(){if(cool>0)return;const p=roster[sel];cool=5;say(p.special+"!",1.2);burst(player.x,player.y,p.trim,18);if(p.nick==="HONEY BADGER"){player.boost=1.4;defenders.forEach(d=>{if(Math.hypot(d.x-player.x,d.y-player.y)<180)d.stun=1.2;});}else if(p.nick==="FREIGHT TRAIN"){player.boost=1.2;defenders.forEach(d=>{if(dist(d,player)<120){d.stun=1.5;combo++;}});}else if(p.nick==="BONES"){player.boost=1.6;}else if(p.nick==="SILK HANDS"){goalie.dir*=-1;puck.vx+=5;}else if(p.nick==="SHOE"){puck.vx=8;puck.vy=0;}else if(p.nick==="DEMPS"){if(Math.random()<.25){puck.vx=13;puck.vy=(Math.random()-.5)*8;}}}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function burst(x,y,col,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*5,vy:(Math.random()-.5)*5,t:1,col});}
function update(dt){if(mode!=="play")return;const p=roster[sel];timeLeft-=dt;cool=Math.max(0,cool-dt);msgT=Math.max(0,msgT-dt);player.boost=Math.max(0,player.boost-dt);if(timeLeft<=0){mode="done";say(score>=3?"MISSION COMPLETE":"SHIFT OVER",9);return;}let ax=0,ay=0;if(keys.a||keys.arrowleft)ax--;if(keys.d||keys.arrowright)ax++;if(keys.w||keys.arrowup)ay--;if(keys.s||keys.arrowdown)ay++;const m=Math.hypot(ax,ay)||1;if(ax)player.face=Math.sign(ax);let sp=(p.speed/100)*(player.boost>0?1.7:1);if(p.nick==="HONEY BADGER")sp*=1.08;player.vx+=(ax/m)*sp*.85;player.vy+=(ay/m)*sp*.85;player.vx*=.86;player.vy*=.86;player.x+=player.vx*5;player.y+=player.vy*5;player.x=Math.max(45,Math.min(880,player.x));player.y=Math.max(95,Math.min(445,player.y));if(Math.abs(player.vx)+Math.abs(player.vy)>1.4)hitMeter=Math.min(100,hitMeter+.3);mate.x+=(player.x-80-mate.x)*.025;mate.y+=(player.y-75-mate.y)*.025;defenders.forEach(d=>{d.stun=Math.max(0,d.stun-dt);if(d.stun<=0){let dx=player.x-d.x,dy=player.y-d.y,dm=Math.hypot(dx,dy)||1;d.vx+=dx/dm*.18;d.vy+=dy/dm*.18;}else{d.vx*=.7;d.vy*=.7;}d.vx*=.85;d.vy*=.85;d.x+=d.vx;d.y+=d.vy;if(dist(d,player)<38&&d.stun<=0){player.vx*=-.4;player.vy*=-.4;say("CONTACT!",.5);}});if(dist(puck,player)<35){puck.vx+=player.vx*.45;puck.vy+=player.vy*.45;}puck.x+=puck.vx;puck.y+=puck.vy;puck.vx*=.985;puck.vy*=.985;if(puck.y<90||puck.y>450)puck.vy*=-.75;puck.y=Math.max(90,Math.min(450,puck.y));if(puck.x<35){puck.x=35;puck.vx*=-.6;}goalie.y+=goalie.dir*2.3;if(goalie.y<190||goalie.y>350)goalie.dir*=-1;if(puck.x>860&&puck.y>210&&puck.y<330&&Math.abs(puck.y-goalie.y)>38){score++;combo++;say(score>=3?"MISSION COMPLETE":"GOAL! "+combo+"x",1.4);burst(890,puck.y,"#ffdc5e",30);puck.x=260;puck.y=270;puck.vx=puck.vy=0;if(score>=3)mode="done";}else if(puck.x>830&&Math.abs(puck.y-goalie.y)<45){puck.vx=-Math.abs(puck.vx)*.9-3;say("SAVE! GLOVE SIDE?",.8);}particles.forEach(q=>{q.x+=q.vx;q.y+=q.vy;q.t-=dt;});particles=particles.filter(q=>q.t>0);}
function drawSelect(){rect(0,0,960,540,"#070b10");txt("SATURDAY MORNING DROP IN CREW",480,40,32,"#f0dbb2","center");txt("HITZ-STYLE PLAYER SELECT",480,70,19,"#28c9d4","center");roster.forEach((p,i)=>card(p,42+(i%4)*227,98+Math.floor(i/4)*150,205,130,i===sel));const p=roster[sel];rect(42,405,876,84,"#07090d");ctx.strokeStyle="#344e64";ctx.strokeRect(42,405,876,84);txt(`${p.name} "${p.nick}" #${p.num}`,60,430,18,"#fff");txt(p.desc,60,456,15,"#ddd");txt("SPECIAL: "+p.special,60,482,16,p.trim);bar("SPD",p.speed,520,430);bar("HST",p.hustle,520,458);bar("STK",p.stick,700,430);bar("PASS",p.pass,700,458);txt("ENTER = START",480,388,22,"#ffdc5e","center");txt("WE DON'T HAVE PRACTICE. WE HAVE SATURDAYS.",480,520,18,"#f0dbb2","center");}
function drawPlay(){rink();const p=roster[sel];drawGoalie();defenders.forEach(d=>drawPixelSkater(d.x,d.y,{num:"",color:"#555",trim:d.stun>0?"#ff3333":"#aaa"},1,-1));drawPixelSkater(mate.x,mate.y,{...p,num:"AI"},.9,1);drawPixelSkater(player.x,player.y,p,1.25,player.face);ctx.fillStyle="#111";ctx.beginPath();ctx.ellipse(puck.x,puck.y,12,6,0,0,Math.PI*2);ctx.fill();particles.forEach(q=>{ctx.globalAlpha=Math.max(0,q.t);ctx.fillStyle=q.col;ctx.fillRect(q.x,q.y,4,4);ctx.globalAlpha=1;});rect(0,0,960,72,"rgba(0,0,0,.85)");txt(`${p.name} "${p.nick}" #${p.num}`,20,28,18);txt(`GOALS ${score}/3`,20,55,18,p.trim);txt(`TIME ${Math.ceil(timeLeft)}`,480,42,22,"#fff","center");txt(`SPECIAL ${cool<=0?"READY":Math.ceil(cool)}`,935,28,16,p.trim,"right");txt(`HITZ ${Math.round(hitMeter)}`,935,55,16,"#ffdc5e","right");if(msgT>0)txt(msg,480,150,34,"#ffdc5e","center");}
function drawDone(){drawPlay();rect(0,0,960,540,"rgba(0,0,0,.72)");txt(msg,480,245,52,"#ffdc5e","center");txt("ENTER: PLAY AGAIN   ESC: ROSTER",480,305,23,"#fff","center");}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);if(mode==="select")drawSelect();else if(mode==="play")drawPlay();else drawDone();requestAnimationFrame(loop);}
requestAnimationFrame(loop);
